import 'sequence_block.dart';

/// A complete training session definition, including its ordered sequence of
/// [SequenceBlock]s.
///
/// [totalDuration] is stored as a persisted field so the Dashboard can display
/// it without re-computing on every build. Call [computedDuration] to derive
/// the value from the current [sequence] (e.g., when saving a draft).
class TrainingSession {
  const TrainingSession({
    required this.id,
    required this.title,
    required this.totalDuration,
    required this.sequence,
  });

  /// Unique session identifier. Generated by [SessionProvider._generateId].
  final String id;

  /// User-facing session name (e.g., '5-3-2 Ladder Drill').
  final String title;

  /// Persisted total duration. Update this with [computedDuration] before
  /// saving so the Dashboard shows accurate data.
  final Duration totalDuration;

  /// Ordered list of blocks defining the training timeline.
  final List<SequenceBlock> sequence;

  // ── Computed Helpers ───────────────────────────────────────────────────────

  /// Sums the [Duration] fields of all [WarmUpBlock] and [DelayBlock] entries.
  ///
  /// [ActionBlock]s have no fixed duration (their length is audio-clip-
  /// dependent) so they do not contribute to this total.
  Duration get computedDuration {
    var total = Duration.zero;
    for (final block in sequence) {
      if (block is WarmUpBlock) total += block.duration;
      if (block is DelayBlock) total += block.duration;
    }
    return total;
  }

  /// Number of [ActionBlock]s in the sequence (useful for the Dashboard tile).
  int get actionCount =>
      sequence.whereType<ActionBlock>().length;

  // ── Serialisation ──────────────────────────────────────────────────────────

  factory TrainingSession.fromJson(Map<String, dynamic> json) =>
      TrainingSession(
        id: json['id'] as String,
        title: json['title'] as String,
        totalDuration:
            Duration(seconds: json['totalDurationSeconds'] as int),
        sequence: (json['sequence'] as List<dynamic>)
            .map((e) => SequenceBlock.fromJson(e as Map<String, dynamic>))
            .toList(),
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'totalDurationSeconds': totalDuration.inSeconds,
        'sequence': sequence.map((b) => b.toJson()).toList(),
      };

  // ── Utility ────────────────────────────────────────────────────────────────

  TrainingSession copyWith({
    String? id,
    String? title,
    Duration? totalDuration,
    List<SequenceBlock>? sequence,
  }) =>
      TrainingSession(
        id: id ?? this.id,
        title: title ?? this.title,
        totalDuration: totalDuration ?? this.totalDuration,
        sequence: sequence ?? this.sequence,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TrainingSession && other.id == id);

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'TrainingSession(id: $id, title: "$title", blocks: ${sequence.length})';
}
