import 'sequence_block.dart';

/// A complete training session definition, including its ordered sequence of
/// [SequenceBlock]s.
///
/// [totalDuration] is stored as a persisted field so the Dashboard can display
/// it without re-computing on every build. Call [computedDuration] to derive
/// the value from the current [sequence] (e.g., when saving a draft).
class TrainingSession {
  const TrainingSession({
    required this.id,
    required this.title,
    required this.totalDuration,
    required this.sequence,
    this.repeatCount = 1,
    this.isInfinite = false,
  });

  /// Unique session identifier. Generated by [SessionProvider._generateId].
  final String id;

  /// User-facing session name (e.g., '5-3-2 Ladder Drill').
  final String title;

  /// Persisted total duration. Update this with [computedDuration] before
  /// saving so the Dashboard shows accurate data.
  final Duration totalDuration;

  /// Ordered list of blocks defining the training timeline.
  final List<SequenceBlock> sequence;

  /// How many times the sequence repeats before stopping. Must be ≥ 1.
  /// Ignored when [isInfinite] is true.
  final int repeatCount;

  /// When true the session loops indefinitely using just_audio's native loop
  /// mode; [repeatCount] is ignored by [AudioService] in this case.
  final bool isInfinite;

  // ── Computed Helpers ───────────────────────────────────────────────────────

  /// Sums the [Duration] fields of all [WarmUpBlock] and [DelayBlock] entries,
  /// then multiplies by [repeatCount] for finite sessions.
  ///
  /// Returns the single-pass duration when [isInfinite] is true (the total is
  /// unbounded, so only one pass is meaningful to display).
  Duration get computedDuration {
    var singlePass = Duration.zero;
    for (final block in sequence) {
      if (block is WarmUpBlock) singlePass += block.duration;
      if (block is DelayBlock) singlePass += block.duration;
    }
    return isInfinite ? singlePass : singlePass * repeatCount;
  }

  /// Number of [ActionBlock]s in the sequence (useful for the Dashboard tile).
  int get actionCount =>
      sequence.whereType<ActionBlock>().length;

  // ── Serialisation ──────────────────────────────────────────────────────────

  factory TrainingSession.fromJson(Map<String, dynamic> json) =>
      TrainingSession(
        id: json['id'] as String,
        title: json['title'] as String,
        totalDuration:
            Duration(seconds: json['totalDurationSeconds'] as int),
        sequence: (json['sequence'] as List<dynamic>)
            .map((e) => SequenceBlock.fromJson(e as Map<String, dynamic>))
            .toList(),
        repeatCount: (json['repeatCount'] as int?) ?? 1,
        isInfinite: (json['isInfinite'] as bool?) ?? false,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'totalDurationSeconds': totalDuration.inSeconds,
        'sequence': sequence.map((b) => b.toJson()).toList(),
        'repeatCount': repeatCount,
        'isInfinite': isInfinite,
      };

  // ── Utility ────────────────────────────────────────────────────────────────

  TrainingSession copyWith({
    String? id,
    String? title,
    Duration? totalDuration,
    List<SequenceBlock>? sequence,
    int? repeatCount,
    bool? isInfinite,
  }) =>
      TrainingSession(
        id: id ?? this.id,
        title: title ?? this.title,
        totalDuration: totalDuration ?? this.totalDuration,
        sequence: sequence ?? this.sequence,
        repeatCount: repeatCount ?? this.repeatCount,
        isInfinite: isInfinite ?? this.isInfinite,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TrainingSession && other.id == id);

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'TrainingSession(id: $id, title: "$title", blocks: ${sequence.length}, '
      'repeatCount: $repeatCount, isInfinite: $isInfinite)';
}
